### ISSUE TITLE
Does not work with extendmatrix 0.4

### ISSUE THREAD

**Issue by Bortechino** [cheind/rmds#1]
With example visualization.rb
```
Traceback (most recent call last):
        9: from /home/alen/Документы/Программирование/Code/visualization.rb:66:in `<main>'
        8: from /home/alen/Документы/Программирование/Code/visualization.rb:36:in `visualization'
        7: from /home/alen/.gem/ruby/2.7.0/gems/rmds-0.2/lib/mds/metric.rb:53:in `projectd'
        6: from /home/alen/.gem/ruby/2.7.0/gems/rmds-0.2/lib/mds/matrix.rb:194:in `ed'
        5: from /home/alen/.gem/ruby/2.7.0/gems/rmds-0.2/lib/mds/interfaces/stdlib_interface.rb:140:in `ed'
        4: from /home/alen/.gem/ruby/2.7.0/gems/extendmatrix-0.4/lib/extendmatrix.rb:1095:in `cJacobiA'
        3: from /home/alen/.gem/ruby/2.7.0/gems/extendmatrix-0.4/lib/extendmatrix.rb:1075:in `cJacobi'
        2: from /home/alen/.gem/ruby/2.7.0/gems/extendmatrix-0.4/lib/extendmatrix.rb:1075:in `clone'
        1: from /home/alen/.gem/ruby/2.7.0/gems/extendmatrix-0.4/lib/extendmatrix.rb:1075:in `initialize_clone'
/home/alen/.gem/ruby/2.7.0/gems/extendmatrix-0.4/lib/extendmatrix.rb:309:in `initialize_copy': undefined method `init_rows' for #<Matrix:0x000055706dec6868> (NoMethodError)
```

**Comment by cheind** [comment]
Hey, thanks for the report. However my last commit is 10 years ago and I hardly know the code anymore. Don't expect a fix anytime soon :)
